# Generated by Django 4.1.3 on 2024-03-24 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_No', models.IntegerField(default=1)),
                ('equipment', models.CharField(default='', max_length=500)),
                ('eqp_description', models.CharField(default='', max_length=500)),
                ('Short_Name', models.CharField(default='', max_length=500)),
                ('shop_No', models.CharField(default='', max_length=500)),
                ('bay', models.CharField(default='', max_length=500)),
                ('column', models.CharField(default='', max_length=500)),
                ('section', models.CharField(default='', max_length=500)),
                ('sec_ELN', models.CharField(default='', max_length=500)),
                ('eqpType', models.CharField(default='', max_length=500)),
                ('mc_Se_No', models.CharField(default='', max_length=500)),
                ('mc_Model', models.CharField(default='', max_length=500)),
                ('Level1', models.CharField(default='', max_length=500)),
                ('level2', models.CharField(default='', max_length=500)),
                ('list1', models.CharField(default='', max_length=500)),
                ('list2', models.CharField(default='', max_length=500)),
                ('manufacturer_Code', models.CharField(default='', max_length=500)),
                ('supplier_Code', models.CharField(default='', max_length=500)),
                ('indian_Agent', models.CharField(default='', max_length=500)),
                ('make', models.CharField(default='', max_length=500)),
                ('cost_in_Rs_Lakh1', models.CharField(default='', max_length=500)),
                ('po_no', models.IntegerField(default=1)),
                ('pO_Date', models.DateField(default=datetime.datetime(2024, 3, 24, 4, 58, 34, 893964))),
                ('unit_Code', models.CharField(default='', max_length=500)),
                ('cost', models.CharField(default='', max_length=500)),
                ('cost_in_Lakh2', models.IntegerField(default=1)),
                ('received_Date', models.DateField(default='')),
                ('date_of_Commisioning', models.DateField(default='')),
                ('pTC_Issued_Date', models.CharField(default='', max_length=500)),
                ('warranty', models.CharField(default='', max_length=500)),
                ('aMC', models.CharField(default='', max_length=500)),
                ('type_of_AMC', models.CharField(default='', max_length=500)),
                ('validity', models.CharField(default='', max_length=500)),
                ('recovery_value', models.CharField(default='', max_length=500)),
                ('age_availability', models.CharField(default='', max_length=500)),
                ('specialization', models.TextField(default='')),
                ('machine_Picture', models.ImageField(default='', upload_to=None)),
                ('pO_Copy', models.ImageField(default='', upload_to=None)),
                ('accumulated_depreciation_till', models.CharField(default='', max_length=500)),
                ('net_Book_Value1', models.CharField(default='', max_length=500)),
                ('give_reference', models.CharField(default='', max_length=500)),
                ('current_Market_value', models.CharField(default='', max_length=500)),
                ('net_Book_Value2', models.CharField(default='', max_length=500)),
                ('whether_Surplus', models.CharField(default='', max_length=500)),
                ('Remarks1', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
