# Generated by Django 4.1.3 on 2024-03-24 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='pO_Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 4, 58, 38, 192529)),
        ),
    ]
