# Generated by Django 4.1.4 on 2024-03-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_signin_emp_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='emp_gender',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='emp_salary',
        ),
    ]
