# Generated by Django 4.1.4 on 2024-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_signin_emp_gender_remove_signin_emp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='signin',
        ),
    ]
